package com.blacksystems.app.entity;


import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Events generated by hbm2java
 */
@Entity
@Table(name = "EVENTS")
public class Event implements java.io.Serializable {

    /**
     * serialVersionUID.
     */
    private static final long serialVersionUID = -2145583178584905893L;
    
    private Long id;
    private String eventTitle;
    private String description;
    private Long versionNumber;
    private Serializable lastModifiedDate;
    private String lastModifiedBy;
    private List<EventRegistration> eventRegistrations = new ArrayList<EventRegistration>(0);

    public Event() {
    }

    public Event(Long id, String eventTitle, String description) {
        this.id = id;
        this.eventTitle = eventTitle;
        this.description = description;
    }

    public Event(Long id, String eventTitle, String description, Long versionNumber, Serializable lastModifiedDate,
        String lastModifiedBy, List<EventRegistration> eventRegistrations) {
        this.id = id;
        this.eventTitle = eventTitle;
        this.description = description;
        this.versionNumber = versionNumber;
        this.lastModifiedDate = lastModifiedDate;
        this.lastModifiedBy = lastModifiedBy;
        this.eventRegistrations = eventRegistrations;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "EVENT_TITLE", nullable = false)
    public String getEventTitle() {
        return this.eventTitle;
    }

    public void setEventTitle(String eventTitle) {
        this.eventTitle = eventTitle;
    }

    @Column(name = "DESCRIPTION", nullable = false)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "VERSION_NUMBER", precision = 22, scale = 0)
    public Long getVersionNumber() {
        return this.versionNumber;
    }

    public void setVersionNumber(Long versionNumber) {
        this.versionNumber = versionNumber;
    }

    @Column(name = "LAST_MODIFIED_DATE")
    public Serializable getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    public void setLastModifiedDate(Serializable lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    @Column(name = "LAST_MODIFIED_BY")
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "events")
    public List<EventRegistration> getEventRegistrations() {
        return this.eventRegistrations;
    }

    public void setEventRegistrations(List<EventRegistration> eventRegistrations) {
        this.eventRegistrations = eventRegistrations;
    }

}
