package com.mindtree.app.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;


/**
 * Employees generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEES", uniqueConstraints = @UniqueConstraint(columnNames = "MID"))
public class Employee implements java.io.Serializable {

	/**
     * serialVersionUID.
     */
    private static final long serialVersionUID = 7749411340048428170L;
    
    private Long id;
	private Long mid;
	private String name;
	private Date joinDate;
	private String email;
	private String versionNumber;
	private Serializable lastModifiedDate;
	private String lastModifiedBy;
    private List<EventRegistration> eventRegistrations = new ArrayList<EventRegistration>(0);

	public Employee() {
	}

	public Employee(Long id, Long mid, String name, Date joinDate, String email) {
		this.id = id;
		this.mid = mid;
		this.name = name;
		this.joinDate = joinDate;
		this.email = email;
	}

	public Employee(Long id, Long mid, String name, Date joinDate, String email, String versionNumber,
			Serializable lastModifiedDate, String lastModifiedBy, List<EventRegistration> eventRegistrations) {
		this.id = id;
		this.mid = mid;
		this.name = name;
		this.joinDate = joinDate;
		this.email = email;
		this.versionNumber = versionNumber;
		this.lastModifiedDate = lastModifiedDate;
		this.lastModifiedBy = lastModifiedBy;
		this.eventRegistrations = eventRegistrations;
	}

	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Basic(optional = false)
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	/*
	@Id
	@GenericGenerator(name="generator", strategy="increment")
	@GeneratedValue(generator="generator")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)*/
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "MID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getMid() {
		return this.mid;
	}

	public void setMid(Long mid) {
		this.mid = mid;
	}

	@Column(name = "NAME", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "JOIN_DATE", nullable = false, length = 7)
	public Date getJoinDate() {
		return this.joinDate;
	}

	public void setJoinDate(Date joinDate) {
		this.joinDate = joinDate;
	}

	@Column(name = "EMAIL", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "VERSION_NUMBER", length = 20)
	public String getVersionNumber() {
		return this.versionNumber;
	}

	public void setVersionNumber(String versionNumber) {
		this.versionNumber = versionNumber;
	}

	@Column(name = "LAST_MODIFIED_DATE")
	public Serializable getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Serializable lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "LAST_MODIFIED_BY")
	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public List<EventRegistration> getEventRegistrations() {
		return this.eventRegistrations;
	}

	public void setEventRegistrations(List<EventRegistration> eventRegistrations) {
		this.eventRegistrations = eventRegistrations;
	}

}
